appname: hiveon-api
httpport: 8090
httpaddr: "127.0.0.1"

sequelize2:
  database: 
  host: 
  port: 3306
  username: 
  password: 

sequelize3:
  database: block
  host: rm-2zefa4845bwys9fb9io.mysql.rds.aliyuncs.com
  port: 3306
  username: 
  password: 

influx:
  host: "127.0.0.1"
  port: 8086
  database: "minerdash"
  username: "admin"
  password: 

redis:
  host: "127.0.0.1"
  port: 6379
  db: 1
  password: ""

postgres:
  host: 
  port: "5432"
  dbName: "oauth"
  user: 
  password: 


security:
  publicURL:  "/api/miner"
  securedURL: "/api/private"
  useCasbin: true

oauth_introspect_url: 
idp_api: 

app:
  config:
    pool:
      workerState: 20m
      pgOneDay: "26 hour"
      poolZoom: "25h"
      hashrate:
        hashrateCul: 4000000000
        hashrateCulDivider: 1200
ZOOM_CONFIG:
  d:
    time: "25h"
    zoom: "20m"

WORKER_STAT_CONFIG:
  d:
    time: "24h"
    zoom: "5m"
