appname: hiveon-api
httpport: 8090
httpaddr: "0.0.0.0"
hiveonEnv: dev

sequelize2:
  database: hiveos_eth
  host: hiveos-eth-prod.cyzben5dhs1h.eu-central-1.rds.amazonaws.com
  port: 3306
  username: 
  password: 

sequelize3:
  database: block
  host: 
  port: 3306
  username: 
  password: 

influx:
  host: "influx"
  port: 8086
  database: "minerdash"
  username: "admin"
  password: 
  
redis:
  host: "redis"
  port: 6379
  db: 1
  password: ""

hiveos:
  authURI: "https://api2.hiveos.farm/api/v2/auth/check"

cache:
  cleanupInterval: 5
  ttl: 300

security:
  publicURL:  "/api/miner"
  securedURL: "/api/private"
  useCasbin: true

oauth_introspect_url: 
idp_api: 


app:
  config:
    pool:
      workerState: 20m
      pgOneDay: "26 hour"
      poolZoom: "25h"
      hashrate:
        hashrateCul: 4000000000
        hashrateCulDivider: 1200

ZOOM_CONFIG:
  d:
    time: "25h"
    zoom: "10m"

WORKER_STAT_CONFIG:
  d:
    time: "24h"
    zoom: "5m"
